/** @file CPoliceRadio.cpp
*  @brief Game's radio wrapper
*
*
*  @author Tyldar (darreugne@gmail.com)
*/

#pragma once

namespace M2
{
    enum E_PoliceEvent : int
    {
        EVENT_COP_REPORT_CHARACTER = 0,
        EVENT_COP_REPORT_CARTHEFT = 1,
        EVENT_STATION_REPORT_SHOTGUN = 3,
        EVENT_STATION_REPORT_MACHINEGUNS = 4,
        EVENT_GET_DENSITY_DOWN = 5,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_1 = 6,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_2 = 7,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_3 = 8,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_4 = 9,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_5 = 10,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_6 = 11,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_7 = 12,
        EVENT_COP_REPORT_ROADBLOCK_OPENING_8 = 13,
        EVENT_POLICE_REPORT_SMALLGUN = 14,
        EVENT_POLICE_REPORT_STREET_COMBAT = 15,
        EVENT_POLICE_REPORT_SPEEDING = 16,
        EVENT_POLICE_REPORT_REDLIGHT_CROSSING = 17,
        EVENT_POLICE_REPORT_CAR_CRASH = 18,
        EVENT_POLICE_REPORT_CRASHING_PUBLICPROPERTY = 19,
        EVENT_POLICE_REPORT_CRASHING_SHOPWINDOW = 20,
        EVENT_POLICE_REPORT_GUN_WITHOUT_LTC = 21,
        EVENT_COP_REPORT_OPENING_SINGLE = 22,
        EVENT_POLICE_REPORT_CONTINUING_STREET_COMBAT = 23,
        EVENT_POLICE_REPORT_CRASHING_POLICECAR = 24,
        EVENT_POLICE_REPORT_COMBAT_ATTACK_ON_POLICEMAN = 25,
        EVENT_POLICE_REPORT_PEDESTRIAN_KILL = 26,
        EVENT_POLICE_REPORT_CARTHEFT = 27,
        EVENT_POLICE_REPORT_SHOOTING_ON_PUBLIC = 28,
        EVENT_POLICE_REPORT_SHOOTING_ON_POLICEOFFICER = 29,
        EVENT_POLICE_REPORT_KILLING_POLICEOFFICER = 30,
        EVENT_POLICE_REPORT_ARREST_AVOIDANCE = 31,
        EVENT_POLICE_REPORT_PEDESTRIAN_HOMICIDE = 32,
        EVENT_POLICE_REPORT_ARMED_SUSPECT = 33,
        EVENT_POLICE_REPORT_TICKET_AVOIDING = 34,
        EVENT_COP_REPORT_CALL_FOR_BACKUP = 35

    };

    class ICPoliceRadio
    {
    public:
    };

    class C_PoliceRadio : public GameClassWrapper<C_PoliceRadio, ICPoliceRadio, 0x1CC80DC>
    {
    public:
        int CreateAnnouncement(E_PoliceEvent policeEvent)
        {
            return Mem::InvokeFunction<Mem::call_this, int>(0xBCF040, this, policeEvent);
        }
    };
};
