#define _CRT_SECURE_NO_WARNINGS
#define D_SCL_SECURE_NO_WARNINGS

#ifdef _DEBUG
#define LIBRG_DEBUG
#endif

#define LIBRG_PLATFORM_ID 5
#define LIBRG_PLATFORM_PROTOCOL 2
#define LIBRG_PLATFORM_BUILD 0

#define LIBRG_IMPLEMENTATION
